/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarBadge: typeof import('./src/components/CarBadge.vue')['default']
    CurrentPointsDisplay: typeof import('./src/components/CurrentPointsDisplay.vue')['default']
    DriverStandingsTable: typeof import('./src/components/DriverStandingsTable.vue')['default']
    LiveRaceInfoDisplay: typeof import('./src/components/LiveRaceInfoDisplay.vue')['default']
    PointsToClinchDisplay: typeof import('./src/components/PointsToClinchDisplay.vue')['default']
    PositionDisplay: typeof import('./src/components/PositionDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartsDisplay: typeof import('./src/components/StartsDisplay.vue')['default']
  }
}
